### ISSUE TITLE
Apache Answer Wants to Say Thank You

### ISSUE THREAD

**Issue by PrimmaAnna** [calmdev/go-devcontainer#1]
Hi Levi L.,

Thank you for building your Q&A platform with us. We'd love to learn more about how you use Answer and your using experience for further improvement. 

I've searched your email address but failed. Would you be willing to share your email address so we can get your insights on using our product? Or, you can drop me an email at anne@answer.dev.

Thanks and have a great day.

Best,
Anne

**Comment by calmdev** [comment]
Hi Anne, 

Thanks for reaching out – my email address is levi@calmdev.com

**Comment by PrimmaAnna** [comment]
> Hi Anne,
> 
> Thanks for reaching out – my email address is [levi@calmdev.com](mailto:levi@calmdev.com)

Hi Levi, I've been trying to reach you via email, but no response so far. Is everything alright?
